from setuptools import setup

setup(
    name='cni_challenge',
    version='',
    packages=['venv.Lib.site-packages.pytz', 'venv.Lib.site-packages.numpy', 'venv.Lib.site-packages.numpy.ma',
              'venv.Lib.site-packages.numpy.ma.tests', 'venv.Lib.site-packages.numpy.doc',
              'venv.Lib.site-packages.numpy.fft', 'venv.Lib.site-packages.numpy.fft.tests',
              'venv.Lib.site-packages.numpy.lib', 'venv.Lib.site-packages.numpy.lib.tests',
              'venv.Lib.site-packages.numpy.core', 'venv.Lib.site-packages.numpy.core.tests',
              'venv.Lib.site-packages.numpy.f2py', 'venv.Lib.site-packages.numpy.f2py.tests',
              'venv.Lib.site-packages.numpy.tests', 'venv.Lib.site-packages.numpy.compat',
              'venv.Lib.site-packages.numpy.compat.tests', 'venv.Lib.site-packages.numpy.linalg',
              'venv.Lib.site-packages.numpy.linalg.tests', 'venv.Lib.site-packages.numpy.random',
              'venv.Lib.site-packages.numpy.random.tests', 'venv.Lib.site-packages.numpy.random.tests.data',
              'venv.Lib.site-packages.numpy.testing', 'venv.Lib.site-packages.numpy.testing.tests',
              'venv.Lib.site-packages.numpy.testing._private', 'venv.Lib.site-packages.numpy.distutils',
              'venv.Lib.site-packages.numpy.distutils.tests', 'venv.Lib.site-packages.numpy.distutils.command',
              'venv.Lib.site-packages.numpy.distutils.fcompiler', 'venv.Lib.site-packages.numpy.matrixlib',
              'venv.Lib.site-packages.numpy.matrixlib.tests', 'venv.Lib.site-packages.numpy.polynomial',
              'venv.Lib.site-packages.numpy.polynomial.tests', 'venv.Lib.site-packages.scipy',
              'venv.Lib.site-packages.scipy.io', 'venv.Lib.site-packages.scipy.io.arff',
              'venv.Lib.site-packages.scipy.io.arff.tests', 'venv.Lib.site-packages.scipy.io.tests',
              'venv.Lib.site-packages.scipy.io.matlab', 'venv.Lib.site-packages.scipy.io.matlab.tests',
              'venv.Lib.site-packages.scipy.io.harwell_boeing', 'venv.Lib.site-packages.scipy.io.harwell_boeing.tests',
              'venv.Lib.site-packages.scipy.odr', 'venv.Lib.site-packages.scipy.odr.tests',
              'venv.Lib.site-packages.scipy._lib', 'venv.Lib.site-packages.scipy._lib.tests',
              'venv.Lib.site-packages.scipy.misc', 'venv.Lib.site-packages.scipy.misc.tests',
              'venv.Lib.site-packages.scipy.stats', 'venv.Lib.site-packages.scipy.stats.tests',
              'venv.Lib.site-packages.scipy.linalg', 'venv.Lib.site-packages.scipy.linalg.tests',
              'venv.Lib.site-packages.scipy.signal', 'venv.Lib.site-packages.scipy.signal.tests',
              'venv.Lib.site-packages.scipy.signal.windows', 'venv.Lib.site-packages.scipy.sparse',
              'venv.Lib.site-packages.scipy.sparse.tests', 'venv.Lib.site-packages.scipy.sparse.linalg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.Lib.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.tests', 'venv.Lib.site-packages.scipy.sparse.linalg.dsolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve',
              'venv.Lib.site-packages.scipy.sparse.linalg.isolve.tests', 'venv.Lib.site-packages.scipy.sparse.csgraph',
              'venv.Lib.site-packages.scipy.sparse.csgraph.tests', 'venv.Lib.site-packages.scipy.cluster',
              'venv.Lib.site-packages.scipy.cluster.tests', 'venv.Lib.site-packages.scipy.fftpack',
              'venv.Lib.site-packages.scipy.fftpack.tests', 'venv.Lib.site-packages.scipy.ndimage',
              'venv.Lib.site-packages.scipy.ndimage.tests', 'venv.Lib.site-packages.scipy.spatial',
              'venv.Lib.site-packages.scipy.spatial.tests', 'venv.Lib.site-packages.scipy.spatial.transform',
              'venv.Lib.site-packages.scipy.spatial.transform.tests', 'venv.Lib.site-packages.scipy.special',
              'venv.Lib.site-packages.scipy.special.tests', 'venv.Lib.site-packages.scipy.special._precompute',
              'venv.Lib.site-packages.scipy.optimize', 'venv.Lib.site-packages.scipy.optimize._lsq',
              'venv.Lib.site-packages.scipy.optimize.tests', 'venv.Lib.site-packages.scipy.optimize._trlib',
              'venv.Lib.site-packages.scipy.optimize._shgo_lib',
              'venv.Lib.site-packages.scipy.optimize.cython_optimize',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr',
              'venv.Lib.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.Lib.site-packages.scipy.constants', 'venv.Lib.site-packages.scipy.constants.tests',
              'venv.Lib.site-packages.scipy.integrate', 'venv.Lib.site-packages.scipy.integrate._ivp',
              'venv.Lib.site-packages.scipy.integrate.tests', 'venv.Lib.site-packages.scipy.interpolate',
              'venv.Lib.site-packages.scipy.interpolate.tests', 'venv.Lib.site-packages.scipy._build_utils',
              'venv.Lib.site-packages.joblib', 'venv.Lib.site-packages.joblib.test',
              'venv.Lib.site-packages.joblib.test.data', 'venv.Lib.site-packages.joblib.externals',
              'venv.Lib.site-packages.joblib.externals.loky', 'venv.Lib.site-packages.joblib.externals.loky.backend',
              'venv.Lib.site-packages.joblib.externals.cloudpickle', 'venv.Lib.site-packages.pandas',
              'venv.Lib.site-packages.pandas.io', 'venv.Lib.site-packages.pandas.io.sas',
              'venv.Lib.site-packages.pandas.io.json', 'venv.Lib.site-packages.pandas.io.excel',
              'venv.Lib.site-packages.pandas.io.formats', 'venv.Lib.site-packages.pandas.io.msgpack',
              'venv.Lib.site-packages.pandas.io.clipboard', 'venv.Lib.site-packages.pandas.api',
              'venv.Lib.site-packages.pandas.api.types', 'venv.Lib.site-packages.pandas.api.extensions',
              'venv.Lib.site-packages.pandas.core', 'venv.Lib.site-packages.pandas.core.ops',
              'venv.Lib.site-packages.pandas.core.util', 'venv.Lib.site-packages.pandas.core.tools',
              'venv.Lib.site-packages.pandas.core.arrays', 'venv.Lib.site-packages.pandas.core.dtypes',
              'venv.Lib.site-packages.pandas.core.sparse', 'venv.Lib.site-packages.pandas.core.groupby',
              'venv.Lib.site-packages.pandas.core.indexes', 'venv.Lib.site-packages.pandas.core.reshape',
              'venv.Lib.site-packages.pandas.core.internals', 'venv.Lib.site-packages.pandas.core.computation',
              'venv.Lib.site-packages.pandas.util', 'venv.Lib.site-packages.pandas._libs',
              'venv.Lib.site-packages.pandas._libs.tslibs', 'venv.Lib.site-packages.pandas.tests',
              'venv.Lib.site-packages.pandas.tests.io', 'venv.Lib.site-packages.pandas.tests.io.sas',
              'venv.Lib.site-packages.pandas.tests.io.json', 'venv.Lib.site-packages.pandas.tests.io.excel',
              'venv.Lib.site-packages.pandas.tests.io.parser', 'venv.Lib.site-packages.pandas.tests.io.formats',
              'venv.Lib.site-packages.pandas.tests.io.msgpack', 'venv.Lib.site-packages.pandas.tests.io.pytables',
              'venv.Lib.site-packages.pandas.tests.api', 'venv.Lib.site-packages.pandas.tests.util',
              'venv.Lib.site-packages.pandas.tests.frame', 'venv.Lib.site-packages.pandas.tests.tools',
              'venv.Lib.site-packages.pandas.tests.arrays', 'venv.Lib.site-packages.pandas.tests.arrays.sparse',
              'venv.Lib.site-packages.pandas.tests.arrays.interval',
              'venv.Lib.site-packages.pandas.tests.arrays.categorical', 'venv.Lib.site-packages.pandas.tests.config',
              'venv.Lib.site-packages.pandas.tests.dtypes', 'venv.Lib.site-packages.pandas.tests.dtypes.cast',
              'venv.Lib.site-packages.pandas.tests.scalar', 'venv.Lib.site-packages.pandas.tests.scalar.period',
              'venv.Lib.site-packages.pandas.tests.scalar.interval',
              'venv.Lib.site-packages.pandas.tests.scalar.timedelta',
              'venv.Lib.site-packages.pandas.tests.scalar.timestamp', 'venv.Lib.site-packages.pandas.tests.series',
              'venv.Lib.site-packages.pandas.tests.series.indexing', 'venv.Lib.site-packages.pandas.tests.sparse',
              'venv.Lib.site-packages.pandas.tests.sparse.frame', 'venv.Lib.site-packages.pandas.tests.sparse.series',
              'venv.Lib.site-packages.pandas.tests.tslibs', 'venv.Lib.site-packages.pandas.tests.window',
              'venv.Lib.site-packages.pandas.tests.generic', 'venv.Lib.site-packages.pandas.tests.groupby',
              'venv.Lib.site-packages.pandas.tests.groupby.aggregate', 'venv.Lib.site-packages.pandas.tests.indexes',
              'venv.Lib.site-packages.pandas.tests.indexes.multi', 'venv.Lib.site-packages.pandas.tests.indexes.period',
              'venv.Lib.site-packages.pandas.tests.indexes.interval',
              'venv.Lib.site-packages.pandas.tests.indexes.datetimes',
              'venv.Lib.site-packages.pandas.tests.indexes.timedeltas', 'venv.Lib.site-packages.pandas.tests.reshape',
              'venv.Lib.site-packages.pandas.tests.reshape.merge', 'venv.Lib.site-packages.pandas.tests.tseries',
              'venv.Lib.site-packages.pandas.tests.tseries.holiday',
              'venv.Lib.site-packages.pandas.tests.tseries.offsets',
              'venv.Lib.site-packages.pandas.tests.tseries.frequencies', 'venv.Lib.site-packages.pandas.tests.indexing',
              'venv.Lib.site-packages.pandas.tests.indexing.interval',
              'venv.Lib.site-packages.pandas.tests.indexing.multiindex', 'venv.Lib.site-packages.pandas.tests.plotting',
              'venv.Lib.site-packages.pandas.tests.resample', 'venv.Lib.site-packages.pandas.tests.extension',
              'venv.Lib.site-packages.pandas.tests.extension.base',
              'venv.Lib.site-packages.pandas.tests.extension.json',
              'venv.Lib.site-packages.pandas.tests.extension.arrow',
              'venv.Lib.site-packages.pandas.tests.extension.decimal', 'venv.Lib.site-packages.pandas.tests.internals',
              'venv.Lib.site-packages.pandas.tests.arithmetic', 'venv.Lib.site-packages.pandas.tests.reductions',
              'venv.Lib.site-packages.pandas.tests.computation', 'venv.Lib.site-packages.pandas.arrays',
              'venv.Lib.site-packages.pandas.compat', 'venv.Lib.site-packages.pandas.compat.numpy',
              'venv.Lib.site-packages.pandas.errors', 'venv.Lib.site-packages.pandas._config',
              'venv.Lib.site-packages.pandas.tseries', 'venv.Lib.site-packages.pandas.plotting',
              'venv.Lib.site-packages.pandas.plotting._matplotlib', 'venv.Lib.site-packages.sklearn',
              'venv.Lib.site-packages.sklearn.svm', 'venv.Lib.site-packages.sklearn.svm.tests',
              'venv.Lib.site-packages.sklearn.tree', 'venv.Lib.site-packages.sklearn.tree.tests',
              'venv.Lib.site-packages.sklearn.tests', 'venv.Lib.site-packages.sklearn.utils',
              'venv.Lib.site-packages.sklearn.utils.tests', 'venv.Lib.site-packages.sklearn.impute',
              'venv.Lib.site-packages.sklearn.impute.tests', 'venv.Lib.site-packages.sklearn.cluster',
              'venv.Lib.site-packages.sklearn.cluster.tests', 'venv.Lib.site-packages.sklearn.compose',
              'venv.Lib.site-packages.sklearn.compose.tests', 'venv.Lib.site-packages.sklearn.metrics',
              'venv.Lib.site-packages.sklearn.metrics.tests', 'venv.Lib.site-packages.sklearn.metrics.cluster',
              'venv.Lib.site-packages.sklearn.metrics.cluster.tests', 'venv.Lib.site-packages.sklearn.mixture',
              'venv.Lib.site-packages.sklearn.mixture.tests', 'venv.Lib.site-packages.sklearn.datasets',
              'venv.Lib.site-packages.sklearn.datasets.tests', 'venv.Lib.site-packages.sklearn.ensemble',
              'venv.Lib.site-packages.sklearn.ensemble.tests',
              'venv.Lib.site-packages.sklearn.ensemble._hist_gradient_boosting',
              'venv.Lib.site-packages.sklearn.ensemble._hist_gradient_boosting.tests',
              'venv.Lib.site-packages.sklearn.manifold', 'venv.Lib.site-packages.sklearn.manifold.tests',
              'venv.Lib.site-packages.sklearn.externals', 'venv.Lib.site-packages.sklearn.externals.joblib',
              'venv.Lib.site-packages.sklearn.neighbors', 'venv.Lib.site-packages.sklearn.neighbors.tests',
              'venv.Lib.site-packages.sklearn.covariance', 'venv.Lib.site-packages.sklearn.covariance.tests',
              'venv.Lib.site-packages.sklearn.inspection', 'venv.Lib.site-packages.sklearn.inspection.tests',
              'venv.Lib.site-packages.sklearn._build_utils', 'venv.Lib.site-packages.sklearn.experimental',
              'venv.Lib.site-packages.sklearn.experimental.tests', 'venv.Lib.site-packages.sklearn.linear_model',
              'venv.Lib.site-packages.sklearn.linear_model.tests', 'venv.Lib.site-packages.sklearn.__check_build',
              'venv.Lib.site-packages.sklearn.decomposition', 'venv.Lib.site-packages.sklearn.decomposition.tests',
              'venv.Lib.site-packages.sklearn.preprocessing', 'venv.Lib.site-packages.sklearn.preprocessing.tests',
              'venv.Lib.site-packages.sklearn.neural_network', 'venv.Lib.site-packages.sklearn.neural_network.tests',
              'venv.Lib.site-packages.sklearn.model_selection', 'venv.Lib.site-packages.sklearn.model_selection.tests',
              'venv.Lib.site-packages.sklearn.semi_supervised', 'venv.Lib.site-packages.sklearn.semi_supervised.tests',
              'venv.Lib.site-packages.sklearn.gaussian_process',
              'venv.Lib.site-packages.sklearn.gaussian_process.tests',
              'venv.Lib.site-packages.sklearn.feature_selection',
              'venv.Lib.site-packages.sklearn.feature_selection.tests',
              'venv.Lib.site-packages.sklearn.feature_extraction',
              'venv.Lib.site-packages.sklearn.feature_extraction.tests',
              'venv.Lib.site-packages.sklearn.cross_decomposition',
              'venv.Lib.site-packages.sklearn.cross_decomposition.tests', 'venv.Lib.site-packages.dateutil',
              'venv.Lib.site-packages.dateutil.tz', 'venv.Lib.site-packages.dateutil.parser',
              'venv.Lib.site-packages.dateutil.zoneinfo', 'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations'],
    url='',
    license='',
    author='Egor',
    author_email='levchenkoegors@gmail.com',
    description=''
)
